package com.smaato.soma.internal.statemachine;

enum LoadingState$Transition {
   TRANSITION_BLOCKLOADING,
   TRANSITION_ERRORLOADING,
   TRANSITION_FINISHLOADING,
   TRANSITION_LOADBANNER,
   TRANSITION_LOADXML,
   TRANSITION_UNBLOCKLOADING;
}
