package com.adsdk.sdk;

public interface Const {
   String AD_EXTRA = "RICH_AD_DATA";
   int AD_FAILED = -1;
   String AD_TYPE_EXTRA = "RICH_AD_TYPE";
   long CACHE_DOWNLOAD_PERIOD = 600000L;
   int CONNECTION_TIMEOUT = 10000;
   String CONNECTION_TYPE_MOBILE_1xRTT = "1xRTT";
   String CONNECTION_TYPE_MOBILE_CDMA = "CDMA";
   String CONNECTION_TYPE_MOBILE_EDGE = "EDGE";
   String CONNECTION_TYPE_MOBILE_EHRPD = "EHRPD";
   String CONNECTION_TYPE_MOBILE_EVDO_0 = "EVDO_0";
   String CONNECTION_TYPE_MOBILE_EVDO_A = "EVDO_A";
   String CONNECTION_TYPE_MOBILE_EVDO_B = "EVDO_B";
   String CONNECTION_TYPE_MOBILE_GPRS = "GPRS";
   String CONNECTION_TYPE_MOBILE_HSDPA = "HSDPA";
   String CONNECTION_TYPE_MOBILE_HSPA = "HSPA";
   String CONNECTION_TYPE_MOBILE_HSPAP = "HSPAP";
   String CONNECTION_TYPE_MOBILE_HSUPA = "HSUPA";
   String CONNECTION_TYPE_MOBILE_IDEN = "IDEN";
   String CONNECTION_TYPE_MOBILE_LTE = "LTE";
   String CONNECTION_TYPE_MOBILE_UMTS = "UMTS";
   String CONNECTION_TYPE_MOBILE_UNKNOWN = "MOBILE";
   String CONNECTION_TYPE_UNKNOWN = "UNKNOWN";
   String CONNECTION_TYPE_WIFI = "WIFI";
   String CONNECTION_TYPE_WIMAX = "WIMAX";
   String ENCODING = "UTF-8";
   String HIDE_BORDER = "<style>* { -webkit-tap-highlight-color: rgba(0,0,0,0);} img {width:100%;height:100%} body {margin: 0; padding: 0}</style>";
   int IMAGE = 0;
   String IMAGE_BODY = "<body style=\'\"\'margin: 0px; padding: 0px; text-align:center;\'\"\'><img src=\'\"\'{0}\'\"\' width=\'\"\'{1}\'dp\"\' height=\'\"\'{2}\'dp\"\'/></body>";
   String INTERSTITIAL_HIDE_BORDER = "<style>* { -webkit-tap-highlight-color: rgba(0,0,0,0);} body {height:100%; width:100%;} img {max-width:100%; max-height:100%; width:auto; height:auto; position: absolute; margin: auto; top: 0; left: 0; right: 0; bottom: 0;}</style>";
   int LIVE = 0;
   CharSequence LOADING = "Loading....";
   int MAX_NUMBER_OF_TRACKING_RETRIES = 5;
   int MRAID = 4;
   int NO_AD = 2;
   String PREFS_DEVICE_ID = "device_id";
   String PROTOCOL_VERSION = "3.0";
   String REDIRECT_URI = "REDIRECT_URI";
   String RESPONSE_ENCODING = "ISO-8859-1";
   int SOCKET_TIMEOUT = 10000;
   String TAG = "ADSDK";
   int TEST = 1;
   int TEXT = 1;
   int TOUCH_DISTANCE = 30;
   String USER_AGENT_PATTERN = "Mozilla/5.0 (Linux; U; Android %1$s; %2$s; %3$s Build/%4$s) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1";
   String VERSION = "6.0.7";
   int VIDEO = 3;
   long VIDEO_LOAD_TIMEOUT = 1200000L;
}
