package com.surpax.a;

import android.content.res.Resources;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.graphics.BitmapFactory.Options;
import android.util.Log;

import com.tcl.hawk.myflashlight.R;

public final class b {
   public float A;
   public int B;
   public int C;
   public Bitmap know_shadow;
   public float E;
   public float F;
   public float G;
   public float H;
   public Bitmap led_knob;
   public float J;
   public float K;
   public float L;
   public float M;
   public float N;
   public float O;
   public final int P = 8;
   public final int Q = 0;
   public Bitmap led_bg;
   public Bitmap led_switch;
   public float c;
   public float d;
   public int e;
   public int f;
   public Bitmap num0;
   public Bitmap num1;
   public Bitmap num2;
   public Bitmap num3;
   public Bitmap num4;
   public Bitmap num5;
   public Bitmap num6;
   public Bitmap num7;
   public Bitmap num8;
   public Bitmap num9;
   public float q;
   public float r;
   public int s;
   public int t;
   public float u;
   public float v;
   public int w;
   public int x;
   public Bitmap led_indicator;
   public float z;

   public final void a(Resources var1, Options var2) {
      this.led_bg = BitmapFactory.decodeResource(var1, R.drawable.panel_led_bg_9, var2);
      Log.d("FlashLightActivity_Test", "background bmps\'s width is:" + this.led_bg.getWidth() + ", height is:" + this.led_bg.getHeight());
      this.led_indicator = BitmapFactory.decodeResource(var1, R.drawable.panel_led_indicator_8, var2);
      this.z = 211.0F;
      this.A = 469.0F;
      this.B = 61;
      this.C = 61;
      this.num0 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_0_8, var2);
      this.num1 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_1_8, var2);
      this.num2 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_2_8, var2);
      this.num3 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_3_8, var2);
      this.num4 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_4_8, var2);
      this.num5 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_5_8, var2);
      this.num6 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_6_8, var2);
      this.num7 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_7_8, var2);
      this.num8 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_8_8, var2);
      this.num9 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_9_8, var2);
      this.q = 228.0F;
      this.r = 211.0F;
      this.s = 24;
      this.t = 35;
      this.led_switch = BitmapFactory.decodeResource(var1, R.drawable.panel_led_switch_8, var2);
      this.c = 162.0F;
      this.d = 452.0F;
      this.e = 155;
      this.f = 254;
      this.led_knob = BitmapFactory.decodeResource(var1, R.drawable.panel_led_knob_8, var2);
      this.know_shadow = BitmapFactory.decodeResource(var1, R.drawable.panel_led_knob_shadow_8, var2);
      this.J = -1106.0F;
      this.K = 0.0F;
      this.L = 480.0F;
      this.M = 151.0F;
      this.H = 167.0F;
      this.G = 480.0F;
      this.E = 0.0F;
      this.F = 0.0F;
      com.surpax.a.a.o = 56;
      com.surpax.a.a.n = 511;
      com.surpax.a.a.m = -105;
   }

   public final void b(Resources var1, Options var2) {
      this.led_bg = BitmapFactory.decodeResource(var1, R.drawable.panel_led_bg_8, var2);
      Log.d("FlashLightActivity_Test", "background bmps\'s width is:" + this.led_bg.getWidth() + ", height is:" + this.led_bg.getHeight());
      this.led_indicator = BitmapFactory.decodeResource(var1, R.drawable.panel_led_indicator_8, var2);
      this.z = 211.0F;
      this.A = 436.0F;
      this.B = 61;
      this.C = 61;
      this.num0 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_0_8, var2);
      this.num1 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_1_8, var2);
      this.num2 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_2_8, var2);
      this.num3 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_3_8, var2);
      this.num4 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_5_8, var2);
      this.num5 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_5_8, var2);
      this.num6 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_6_8, var2);
      this.num7 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_7_8, var2);
      this.num8 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_8_8, var2);
      this.num9 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_9_8, var2);
      this.q = 228.0F;
      this.r = 211.0F;
      this.s = 24;
      this.t = 35;
      this.led_switch = BitmapFactory.decodeResource(var1, R.drawable.panel_led_switch_8, var2);
      this.c = 163.0F;
      this.d = 417.0F;
      this.e = 155;
      this.f = 254;
      this.led_knob = BitmapFactory.decodeResource(var1, R.drawable.panel_led_knob_8, var2);
      this.know_shadow = BitmapFactory.decodeResource(var1, R.drawable.panel_led_knob_shadow_8, var2);
      this.J = -1106.0F;
      this.K = 0.0F;
      this.L = 480.0F;
      this.M = 151.0F;
      this.H = 167.0F;
      this.G = 480.0F;
      this.E = 0.0F;
      this.F = 0.0F;
      com.surpax.a.a.o = 56;
      com.surpax.a.a.n = 511;
      com.surpax.a.a.m = -108;
   }

   public final void c(Resources var1, Options var2) {
      this.led_bg = BitmapFactory.decodeResource(var1, R.drawable.panel_led_bg_6, var2);
      this.led_indicator = BitmapFactory.decodeResource(var1, R.drawable.panel_led_indicator_6, var2);
      this.z = 204.0F;
      this.A = 318.0F;
      this.B = 55;
      this.C = 55;
      this.num0 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_0_6, var2);
      this.num1 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_1_6, var2);
      this.num2 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_2_6, var2);
      this.num3 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_3_6, var2);
      this.num4 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_4_6, var2);
      this.num5 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_5_6, var2);
      this.num6 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_6_6, var2);
      this.num7 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_7_6, var2);
      this.num8 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_8_6, var2);
      this.num9 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_9_6, var2);
      this.q = 218.0F;
      this.r = 176.0F;
      this.s = 22;
      this.t = 31;
      this.led_switch = BitmapFactory.decodeResource(var1, R.drawable.panel_led_switch_6, var2);
      this.c = 159.0F;
      this.d = 301.0F;
      this.e = 140;
      this.f = 196;
      this.led_knob = BitmapFactory.decodeResource(var1, R.drawable.panel_led_knob_6, var2);
      this.know_shadow = BitmapFactory.decodeResource(var1, R.drawable.panel_led_knob_shadow_6, var2);
      this.J = -1105.0F;
      this.K = 0.0F;
      this.L = 480.0F;
      this.M = 137.0F;
      this.H = 151.0F;
      this.G = 480.0F;
      this.E = 0.0F;
      this.F = 0.0F;
      com.surpax.a.a.o = 56;
      com.surpax.a.a.n = 511;
      com.surpax.a.a.m = -66;
   }

   public final void d(Resources var1, Options var2) {
      this.led_bg = BitmapFactory.decodeResource(var1, R.drawable.panel_led_bg_4, var2);
      this.led_indicator = BitmapFactory.decodeResource(var1, R.drawable.panel_led_indicator_4, var2);
      this.z = 142.0F;
      this.A = 249.0F;
      this.B = 38;
      this.C = 37;
      this.num0 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_0_4, var2);
      this.num1 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_1_4, var2);
      this.num2 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_2_4, var2);
      this.num3 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_3_4, var2);
      this.num4 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_4_4, var2);
      this.num5 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_5_4, var2);
      this.num6 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_6_4, var2);
      this.num7 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_7_4, var2);
      this.num8 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_8_4, var2);
      this.num9 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_9_4, var2);
      this.q = 151.0F;
      this.r = 126.0F;
      this.s = 17;
      this.t = 24;
      this.led_switch = BitmapFactory.decodeResource(var1, R.drawable.panel_led_switch_4, var2);
      this.c = 113.0F;
      this.d = 240.0F;
      this.e = 92;
      this.f = 151;
      this.led_knob = BitmapFactory.decodeResource(var1, R.drawable.panel_led_knob_4, var2);
      this.know_shadow = BitmapFactory.decodeResource(var1, R.drawable.panel_led_knob_shadow_4, var2);
      this.J = -667.0F;
      this.K = 0.0F;
      this.L = 320.0F;
      this.M = 90.0F;
      this.H = 91.0F;
      this.G = 320.0F;
      this.E = 0.0F;
      this.F = 0.0F;
      com.surpax.a.a.o = 36;
      com.surpax.a.a.n = 328;
      com.surpax.a.a.m = -66;
   }

   public final void e(Resources var1, Options var2) {
      this.led_bg = BitmapFactory.decodeResource(var1, R.drawable.panel_led_bg_12, var2);
      Log.d("FlashLightActivity_Test", "background bmps\'s width is:" + this.led_bg.getWidth() + ", height is:" + this.led_bg.getHeight());
      this.led_indicator = BitmapFactory.decodeResource(var1, R.drawable.panel_led_indicator_12, var2);
      this.z = 320.0F;
      this.A = 767.0F;
      this.B = 82;
      this.C = 82;
      this.num0 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_0_12, var2);
      this.num1 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_1_12, var2);
      this.num2 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_2_12, var2);
      this.num3 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_3_12, var2);
      this.num4 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_4_12, var2);
      this.num5 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_5_12, var2);
      this.num6 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_6_12, var2);
      this.num7 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_7_12, var2);
      this.num8 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_8_12, var2);
      this.num9 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_9_12, var2);
      this.q = 344.0F;
      this.r = 370.0F;
      this.s = 33;
      this.t = 48;
      this.led_switch = BitmapFactory.decodeResource(var1, R.drawable.panel_led_switch_12, var2);
      this.c = 253.0F;
      this.d = 745.0F;
      this.e = 211;
      this.f = 331;
      this.led_knob = BitmapFactory.decodeResource(var1, R.drawable.panel_led_knob_12, var2);
      this.know_shadow = BitmapFactory.decodeResource(var1, R.drawable.panel_led_knob_shadow_12, var2);
      this.J = -1180.0F;
      this.K = 0.0F;
      this.L = 720.0F;
      this.M = 223.0F;
      this.H = 507.0F;
      this.G = 720.0F;
      this.E = 0.0F;
      this.F = 0.0F;
      com.surpax.a.a.o = 83;
      com.surpax.a.a.n = 830;
      com.surpax.a.a.m = -230;
   }

   public final void f(Resources var1, Options var2) {
      this.led_bg = BitmapFactory.decodeResource(var1, R.drawable.panel_led_bg_11, var2);
      Log.d("FlashLightActivity_Test", "background bmps\'s width is:" + this.led_bg.getWidth() + ", height is:" + this.led_bg.getHeight());
      this.led_indicator = BitmapFactory.decodeResource(var1, R.drawable.panel_led_indicator_12, var2);
      this.z = 320.0F;
      this.A = 699.0F;
      this.B = 82;
      this.C = 82;
      this.num0 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_0_12, var2);
      this.num1 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_1_12, var2);
      this.num2 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_2_12, var2);
      this.num3 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_3_12, var2);
      this.num4 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_4_12, var2);
      this.num5 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_5_12, var2);
      this.num6 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_6_12, var2);
      this.num7 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_7_12, var2);
      this.num8 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_8_12, var2);
      this.num9 = BitmapFactory.decodeResource(var1, R.drawable.panel_led_num_9_12, var2);
      this.q = 344.0F;
      this.r = 370.0F;
      this.s = 33;
      this.t = 48;
      this.led_switch = BitmapFactory.decodeResource(var1, R.drawable.panel_led_switch_12, var2);
      this.c = 253.0F;
      this.d = 675.0F;
      this.e = 211;
      this.f = 331;
      this.led_knob = BitmapFactory.decodeResource(var1, R.drawable.panel_led_knob_12, var2);
      this.know_shadow = BitmapFactory.decodeResource(var1, R.drawable.panel_led_knob_shadow_12, var2);
      this.J = -1180.0F;
      this.K = 0.0F;
      this.L = 720.0F;
      this.M = 223.0F;
      this.H = 248.0F;
      this.G = 720.0F;
      this.E = 0.0F;
      this.F = 0.0F;
      com.surpax.a.a.o = 83;
      com.surpax.a.a.n = 830;
      com.surpax.a.a.m = -160;
   }
}
