package com.inmobi.commons.analytics.iat.impl;

public enum AdTrackerConstants$StatusCode {
   APP_ANALYTICS_PREVIOUSLY_UPLOADED,
   APP_ANALYTICS_UPLOAD_FAILURE,
   APP_ANALYTICS_UPLOAD_SUCCESS,
   APP_CONTEXT_NULL,
   APP_NOT_CONNECTED,
   ODIN1_NULL,
   RELOAD_WEBVIEW_ERROR;
}
