package com.inmobi.commons.analytics.iat.impl;

public enum Goal$State {
   ENQUEUE_PENDING,
   ENQUEUE_REQUESTED,
   ENQUEUE_SUCCEEDED,
   REFERRER_ACQUIRED,
   REFERRER_REQUESTED,
   REPORTING_COMPLETED,
   REPORTING_FAILED,
   REPORTING_REQUESTED,
   REPORTING_TIMED_OUT;
}
